name: Release Please

on:
  push:
    branches:
      - main  # Change this if your default branch is different

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node  # Since React projects use Node.js
          token: ${{ secrets.GITHUB_TOKEN }}
